version: '2'
services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      - CASSANDRA_CQL_PORT_NUMBER=9042